### ISSUE TITLE
GUI - NullPointerException

### ISSUE THREAD

**Issue by savesCZ** [TomasCZE7/HackerTools#3]
**Describe the bug**
HackerTools are giving me an error, when a player tries to move item from their inventory to GUI.

**To Reproduce**
1. Open GUI
2. Take item from your inventory
3. Move it into the GUI
4. Watch the console

**Expected behavior**
There shouldn't be an error.

**Error**
https://pastebin.com/0rNpVA41

**Additional context**
This error is not major and it doesn't block any action. It is just annoying.

**Edited by owner of the project:** Post translated to the english language.

**Comment by TomasCZE7** [comment]
### Issue fixed

I forgot to add some conditions to prevent this NPE. I'm sorry for any inconveniences.
